import { zodResolver } from "@hookform/resolvers/zod";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useForm, useWatch } from "react-hook-form";
import { useState } from "react";
import type { ReactNode } from "react";
import { z } from "zod";
import { categoryQueryKey, listCategories } from "../../categories/api/categoriesApi";
import type { Category, PageResponse, RecurringTransaction } from "../../../shared/api/models";
import { useNotifications } from "../../../shared/notifications/useNotifications";
import { createRecurringTransaction, deleteRecurringTransaction, listRecurringTransactions, recurringTransactionQueryKey, updateRecurringTransaction } from "../api/recurringTransactionsApi";
import type { RecurringTransactionInput } from "../api/recurringTransactionsApi";
import styles from "./RecurringTransactionsManager.module.css";

const ruleSchema = z.object({
  categoryId: z.string().uuid("Select a category."), amount: z.string().regex(/^\d{1,15}(?:\.\d{1,4})?$/, "Enter a positive amount with up to 4 decimal places.").refine((value) => Number(value) > 0, "Enter a positive amount."),
  currency: z.string().regex(/^[A-Z]{3}$/, "Use a three-letter uppercase currency code."), exchangeRateToBase: z.string().regex(/^\d{1,11}(?:\.\d{1,8})?$/, "Enter a positive exchange rate with up to 8 decimal places.").refine((value) => Number(value) > 0, "Enter a positive exchange rate."),
  description: z.string().max(1000, "Use no more than 1000 characters."), transactionType: z.enum(["INCOME", "EXPENSE"]), dayOfMonth: z.number().int().min(1, "Select a day from 1 to 31.").max(31, "Select a day from 1 to 31."), startDate: z.string().date("Enter a start date."), active: z.boolean(),
});
type RuleFormValues = z.infer<typeof ruleSchema>;
const initialValues: RuleFormValues = { categoryId: "", amount: "", currency: "USD", exchangeRateToBase: "1", description: "", transactionType: "EXPENSE", dayOfMonth: 1, startDate: "", active: true };

function valuesFor(rule: RecurringTransaction): RuleFormValues { return { categoryId: rule.categoryId, amount: rule.amount, currency: rule.currency, exchangeRateToBase: rule.exchangeRateToBase, description: rule.description ?? "", transactionType: rule.transactionType, dayOfMonth: rule.dayOfMonth, startDate: rule.startDate, active: rule.active }; }
function inputFor(values: RuleFormValues): RecurringTransactionInput { return { ...values, description: values.description === "" ? null : values.description }; }
async function listAllCategories(signal?: AbortSignal): Promise<Category[]> { const categories: Category[] = []; let page = 0; do { const response: PageResponse<Category> = await listCategories(page, signal, 100); categories.push(...response.items); page += 1; if (page >= response.page.totalPages) return categories; } while (!signal?.aborted); return categories; }

function RuleForm({ rule, onClose }: { rule: RecurringTransaction | null; onClose: () => void }) {
  const queryClient = useQueryClient(); const { notify } = useNotifications();
  const categoriesQuery = useQuery({ queryKey: [...categoryQueryKey, "all"], queryFn: ({ signal }) => listAllCategories(signal) });
  const { control, formState: { errors, isSubmitting }, handleSubmit, register } = useForm<RuleFormValues>({ defaultValues: rule === null ? initialValues : valuesFor(rule), resolver: zodResolver(ruleSchema) });
  const transactionType = useWatch({ control, name: "transactionType" });
  const mutation = useMutation({ mutationFn: (values: RuleFormValues) => rule === null ? createRecurringTransaction(inputFor(values)) : updateRecurringTransaction(rule, inputFor(values)), onSuccess: () => { void queryClient.invalidateQueries({ queryKey: recurringTransactionQueryKey }); notify(rule === null ? "Recurring rule created." : "Recurring rule updated."); onClose(); } });
  async function submit(values: RuleFormValues): Promise<void> { try { await mutation.mutateAsync(values); } catch { /* The safe server error is shown below. */ } }
  return <form className={styles.form} noValidate onSubmit={handleSubmit(submit)}><h2>{rule === null ? "New recurring rule" : "Edit recurring rule"}</h2>
    <Field error={errors.categoryId?.message} label="Category" name="categoryId"><select id="recurring-categoryId" {...register("categoryId")}><option value="">Select a category</option>{categoriesQuery.data?.filter((category) => category.transactionType === transactionType).map((category) => <option key={category.id} value={category.id}>{category.icon} {category.name}</option>)}</select></Field>
    <Field error={errors.amount?.message} label="Amount" name="amount"><input id="recurring-amount" type="text" {...register("amount")} /></Field><Field error={errors.currency?.message} label="Currency" name="currency"><input id="recurring-currency" type="text" {...register("currency")} /></Field><Field error={errors.exchangeRateToBase?.message} label="Exchange rate to base currency" name="exchangeRateToBase"><input id="recurring-exchangeRateToBase" type="text" {...register("exchangeRateToBase")} /></Field>
    <Field error={errors.transactionType?.message} label="Type" name="transactionType"><select id="recurring-transactionType" {...register("transactionType")}><option value="EXPENSE">Expense</option><option value="INCOME">Income</option></select></Field><Field error={errors.dayOfMonth?.message} label="Day of month" name="dayOfMonth"><input id="recurring-dayOfMonth" max="31" min="1" type="number" {...register("dayOfMonth", { valueAsNumber: true })} /></Field><Field error={errors.startDate?.message} label="Start date" name="startDate"><input id="recurring-startDate" type="date" {...register("startDate")} /></Field><Field error={errors.description?.message} label="Description" name="description"><input id="recurring-description" type="text" {...register("description")} /></Field>
    <label className={styles.checkbox}><input type="checkbox" {...register("active")} /> Active rule</label>{categoriesQuery.isError && <p className={styles.error} role="alert">We could not load categories. Please try again.</p>}{mutation.isError && <p className={styles.error} role="alert">We could not save the recurring rule. Please try again.</p>}<div className={styles.actions}><button className={styles.primaryButton} disabled={isSubmitting} type="submit">{isSubmitting ? "Saving…" : "Save rule"}</button><button className={styles.secondaryButton} disabled={isSubmitting} onClick={onClose} type="button">Cancel</button></div></form>;
}
function Field({ children, error, label, name }: { children: ReactNode; error?: string; label: string; name: string }) { const id = `recurring-${name}`; return <div className={styles.field}><label htmlFor={id}>{label}</label>{children}{error && <p className={styles.error} role="alert">{error}</p>}</div>; }

export function RecurringTransactionsManager() {
  const [page, setPage] = useState(0); const [editedRule, setEditedRule] = useState<RecurringTransaction | null | undefined>(); const queryClient = useQueryClient(); const { notify } = useNotifications();
  const rulesQuery = useQuery({ queryKey: [...recurringTransactionQueryKey, page], queryFn: ({ signal }) => listRecurringTransactions(page, signal) });
  const activation = useMutation({ mutationFn: (rule: RecurringTransaction) => updateRecurringTransaction(rule, { active: !rule.active }), onSuccess: (rule) => { void queryClient.invalidateQueries({ queryKey: recurringTransactionQueryKey }); notify(rule.active ? "Recurring rule activated." : "Recurring rule paused."); } });
  const deletion = useMutation({ mutationFn: deleteRecurringTransaction, onSuccess: () => { void queryClient.invalidateQueries({ queryKey: recurringTransactionQueryKey }); notify("Recurring rule deleted."); } });
  return <section className={styles.page}><header className={styles.header}><div><h1>Recurring transactions</h1><p>Schedule monthly income and expenses.</p></div><button className={styles.primaryButton} onClick={() => setEditedRule(null)} type="button">Add recurring rule</button></header>{editedRule !== undefined && <RuleForm key={editedRule?.id ?? "new"} onClose={() => setEditedRule(undefined)} rule={editedRule} />}{rulesQuery.isPending && <p role="status">Loading recurring rules…</p>}{rulesQuery.isError && <p className={styles.error} role="alert">We could not load recurring rules. Please refresh the page.</p>}{rulesQuery.data?.items.length === 0 && <p className={styles.empty}>No recurring rules yet. Add one to schedule future transactions.</p>}{rulesQuery.data !== undefined && rulesQuery.data.items.length > 0 && <ul className={styles.list}>{rulesQuery.data.items.map((rule) => <li className={styles.rule} key={rule.id}><div><strong>{rule.amount} {rule.currency} · {rule.transactionType === "EXPENSE" ? "Expense" : "Income"}</strong><p>{rule.description ?? "No description"}</p><small>Day {rule.dayOfMonth} · Next: {rule.nextOccurrenceDate} · {rule.active ? "Active" : "Paused"}</small></div><div className={styles.actions}><button onClick={() => activation.mutate(rule)} type="button">{rule.active ? "Pause rule" : "Activate rule"}</button><button onClick={() => setEditedRule(rule)} type="button">Edit rule</button><button disabled={deletion.isPending} onClick={() => deletion.mutate(rule)} type="button">Delete rule</button></div></li>)}</ul>}{rulesQuery.data !== undefined && rulesQuery.data.page.totalPages > 1 && <nav aria-label="Recurring rule pages" className={styles.pagination}><button disabled={page === 0} onClick={() => setPage((value) => value - 1)} type="button">Previous page</button><span>Page {page + 1} of {rulesQuery.data.page.totalPages}</span><button disabled={page + 1 === rulesQuery.data.page.totalPages} onClick={() => setPage((value) => value + 1)} type="button">Next page</button></nav>}</section>;
}
