import { useQuery } from "@tanstack/react-query";
import { useState } from "react";
import type { AuditEntityType, AuditLog } from "../../../shared/api/models";
import { auditLogQueryKey, listAuditLogs } from "../api/auditApi";
import styles from "./AuditLogManager.module.css";

function State({ label, state }: { label: string; state: AuditLog["beforeState"] }) {
  return <section className={styles.state}><h3>{label}</h3>{state === null ? <p>Not available</p> : <dl>{Object.entries(state).map(([key, value]) => <div key={key}><dt>{key}</dt><dd>{value ?? "Not set"}</dd></div>)}</dl>}</section>;
}

export function AuditLogManager() {
  const [entityType, setEntityType] = useState<AuditEntityType>("TRANSACTION"); const [entityId, setEntityId] = useState(""); const [submittedEntityId, setSubmittedEntityId] = useState(""); const [page, setPage] = useState(0);
  const auditQuery = useQuery({ queryKey: [...auditLogQueryKey, entityType, submittedEntityId, page], queryFn: ({ signal }) => listAuditLogs(entityType, submittedEntityId, page, signal) });
  return <section className={styles.page}><header className={styles.header}><div><h1>Audit log</h1><p>Review changes to your transactions and budgets.</p></div></header><form className={styles.filters} onSubmit={(event) => { event.preventDefault(); setSubmittedEntityId(entityId); setPage(0); }}><div><label htmlFor="audit-entity-type">Resource type</label><select id="audit-entity-type" onChange={(event) => { setEntityType(event.target.value === "BUDGET" ? "BUDGET" : "TRANSACTION"); setPage(0); }} value={entityType}><option value="TRANSACTION">Transactions</option><option value="BUDGET">Budgets</option></select></div><div><label htmlFor="audit-entity-id">Resource ID</label><input id="audit-entity-id" onChange={(event) => setEntityId(event.target.value)} placeholder="Optional UUID" type="text" value={entityId} /></div><button type="submit">Apply filters</button></form>{auditQuery.isPending && <p role="status">Loading audit log…</p>}{auditQuery.isError && <p className={styles.error} role="alert">We could not load the audit log. Please refresh the page.</p>}{auditQuery.data?.items.length === 0 && <p className={styles.empty}>No audit entries match these filters.</p>}{auditQuery.data !== undefined && auditQuery.data.items.length > 0 && <ol className={styles.entries}>{auditQuery.data.items.map((entry) => <li key={entry.id}><header><strong>{entry.action}</strong><span>{entry.entityType.toLowerCase()} · {entry.occurredAt}</span></header><p>Resource: {entry.entityId}</p><div className={styles.states}><State label="Before" state={entry.beforeState} /><State label="After" state={entry.afterState} /></div></li>)}</ol>}{auditQuery.data !== undefined && auditQuery.data.page.totalPages > 1 && <nav aria-label="Audit log pages" className={styles.pagination}><button disabled={page === 0} onClick={() => setPage((value) => value - 1)} type="button">Previous page</button><span>Page {page + 1} of {auditQuery.data.page.totalPages}</span><button disabled={page + 1 === auditQuery.data.page.totalPages} onClick={() => setPage((value) => value + 1)} type="button">Next page</button></nav>}</section>;
}
